steps:
  # Build the container image using Docker (disable auto-detection)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rocket-trading-app:$COMMIT_SHA'
      - '--no-cache'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rocket-trading-app:$COMMIT_SHA']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'rocket-trading-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rocket-trading-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'

# Store images in Google Container Registry
images:
  - gcr.io/$PROJECT_ID/rocket-trading-app:$COMMIT_SHA

# Build options - Force Docker only
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Build timeout
timeout: 1200s

# Substitutions to prevent auto-detection
substitutions:
  _USE_DOCKER: 'true'
  _DISABLE_BUILDPACKS: 'true' 